-- PostgreSQL Schema for Supabase (Combined)

-- ==========================================
-- Part 1: Healthcare BBC Tables
-- ==========================================

-- 1. 用户表 (user_info)
CREATE TABLE IF NOT EXISTS user_info (
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wechat_id VARCHAR(64) UNIQUE NOT NULL,
    name VARCHAR(32) NOT NULL,
    gender SMALLINT,
    age INT,
    phone VARCHAR(16),
    email VARCHAR(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status SMALLINT DEFAULT 1
);

-- 2. 健康档案表 (health_record)
CREATE TABLE IF NOT EXISTS health_record (
    record_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    height DECIMAL(5,2),
    weight DECIMAL(5,2),
    blood_type VARCHAR(8),
    medical_history TEXT,
    allergy_history TEXT,
    family_history TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. 健康监测数据表 (health_monitor_data)
CREATE TABLE IF NOT EXISTS health_monitor_data (
    data_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    data_type VARCHAR(32) NOT NULL,
    data_value DECIMAL(10,2) NOT NULL,
    data_unit VARCHAR(16) NOT NULL,
    measure_time TIMESTAMP NOT NULL,
    device_type VARCHAR(32),
    device_id VARCHAR(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. 健康计划表 (health_plan)
CREATE TABLE IF NOT EXISTS health_plan (
    plan_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    plan_type VARCHAR(32) NOT NULL,
    plan_content TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. 保险产品表 (insurance_product)
CREATE TABLE IF NOT EXISTS insurance_product (
    product_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_code VARCHAR(32) UNIQUE NOT NULL,
    product_name VARCHAR(128) NOT NULL,
    product_type VARCHAR(32) NOT NULL,
    min_age INT NOT NULL,
    max_age INT NOT NULL,
    min_premium DECIMAL(12,2) NOT NULL,
    max_premium DECIMAL(12,2) NOT NULL,
    coverage_amount DECIMAL(15,2) NOT NULL,
    coverage_period VARCHAR(32) NOT NULL,
    payment_period VARCHAR(32) NOT NULL,
    health_requirements TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status SMALLINT DEFAULT 1
);

-- 6. 保单表 (insurance_policy)
CREATE TABLE IF NOT EXISTS insurance_policy (
    policy_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    policy_no VARCHAR(32) UNIQUE NOT NULL,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    premium_amount DECIMAL(12,2) NOT NULL,
    coverage_amount DECIMAL(15,2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    payment_period VARCHAR(32) NOT NULL,
    status SMALLINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 7. 用户标签表 (user_tag)
CREATE TABLE IF NOT EXISTS user_tag (
    tag_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    tag_category VARCHAR(32),
    tag_name VARCHAR(64) NOT NULL,
    tag_source VARCHAR(32),
    confidence_score DECIMAL(3,2) DEFAULT 1.0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. 健康权益表 (health_benefit)
CREATE TABLE IF NOT EXISTS health_benefit (
    benefit_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    benefit_name VARCHAR(128) NOT NULL,
    benefit_type VARCHAR(32),
    description TEXT,
    valid_period INT,
    status SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. 用户权益关联表 (user_benefit_rel)
CREATE TABLE IF NOT EXISTS user_benefit_rel (
    rel_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    benefit_id BIGINT NOT NULL,
    source_type VARCHAR(32),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status SMALLINT DEFAULT 1,
    use_time TIMESTAMP
);

-- 10. 客服消息表 (customer_message)
CREATE TABLE IF NOT EXISTS customer_message (
    message_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wechat_external_user_id VARCHAR(64) NOT NULL,
    from_user_id VARCHAR(64),
    to_user_id VARCHAR(64),
    message_type VARCHAR(32) NOT NULL,
    content TEXT,
    media_url VARCHAR(512),
    direction SMALLINT NOT NULL,
    status SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 11. 客服会话表 (customer_service_session)
CREATE TABLE IF NOT EXISTS customer_service_session (
    session_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    wechat_external_user_id VARCHAR(64) NOT NULL,
    agent_id BIGINT,
    agent_name VARCHAR(32),
    status SMALLINT DEFAULT 1,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 12. AI意图表 (ai_intent)
CREATE TABLE IF NOT EXISTS ai_intent (
    intent_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    intent_code VARCHAR(32) UNIQUE NOT NULL,
    intent_name VARCHAR(64) NOT NULL,
    intent_category VARCHAR(32),
    target_role VARCHAR(32),
    keywords TEXT,
    confidence_threshold DECIMAL(3,2) DEFAULT 0.7,
    priority INT DEFAULT 0,
    status SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 初始化AI意图数据
INSERT INTO ai_intent (intent_code, intent_name, intent_category, target_role, keywords, priority) VALUES
('HEALTH_CONSULT', '健康咨询', 'HEALTH', 'DOCTOR', '血压,血糖,症状,疾病,医生,看病,不舒服,疼痛', 10),
('INSURANCE_CONSULT', '保险咨询', 'INSURANCE', 'ADVISOR', '保险,保单,理赔,保障,投保,保费,保额', 10),
('BENEFIT_CONSULT', '权益咨询', 'BENEFIT', 'MANAGER', '权益,体检,绿通,问诊,服务,优惠', 10),
('URGENT_MEDICAL', '紧急医疗', 'HEALTH', 'DOCTOR', '紧急,急救,严重,危险,马上,立刻', 20),
('COMPLAINT', '投诉建议', 'GENERAL', 'MANAGER', '投诉,不满,建议,反馈,问题', 15),
('GENERAL_CHAT', '通用对话', 'GENERAL', 'AI', '你好,您好,谢谢,再见,在吗', 5)
ON CONFLICT (intent_code) DO NOTHING;

-- 初始化测试用户
INSERT INTO user_info (wechat_id, name, gender, age, phone, status) VALUES
('test123', '测试用户', 1, 30, '13800138000', 1),
('wmABC123', '张三', 1, 35, '13900139000', 1)
ON CONFLICT (wechat_id) DO NOTHING;


-- ==========================================
-- Part 2: Healthcare Admin Tables
-- ==========================================

-- 用户表
CREATE TABLE IF NOT EXISTS sys_user (
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    real_name VARCHAR(64),
    phone VARCHAR(16),
    email VARCHAR(64),
    avatar VARCHAR(255),
    gender SMALLINT DEFAULT 0,
    dept_id BIGINT,
    status SMALLINT DEFAULT 1,
    login_ip VARCHAR(64),
    login_time TIMESTAMP,
    wechat_user_id VARCHAR(64),
    remark VARCHAR(255),
    create_by BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted SMALLINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_sys_user_username ON sys_user(username);
CREATE INDEX IF NOT EXISTS idx_sys_user_phone ON sys_user(phone);
CREATE INDEX IF NOT EXISTS idx_sys_user_dept_id ON sys_user(dept_id);
CREATE INDEX IF NOT EXISTS idx_sys_user_status ON sys_user(status);

-- 角色表
CREATE TABLE IF NOT EXISTS sys_role (
    role_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_code VARCHAR(64) NOT NULL UNIQUE,
    role_name VARCHAR(64) NOT NULL,
    role_type SMALLINT DEFAULT 1,
    data_scope SMALLINT DEFAULT 1,
    description VARCHAR(255),
    sort_order INT DEFAULT 0,
    status SMALLINT DEFAULT 1,
    create_by BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted SMALLINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_sys_role_role_code ON sys_role(role_code);
CREATE INDEX IF NOT EXISTS idx_sys_role_status ON sys_role(status);

-- 用户角色关联表
CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_sys_user_role_user_id ON sys_user_role(user_id);
CREATE INDEX IF NOT EXISTS idx_sys_user_role_role_id ON sys_user_role(role_id);

-- 权限表
CREATE TABLE IF NOT EXISTS sys_permission (
    permission_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_id BIGINT DEFAULT 0,
    permission_code VARCHAR(128) NOT NULL UNIQUE,
    permission_name VARCHAR(64) NOT NULL,
    permission_type SMALLINT NOT NULL,
    path VARCHAR(128),
    component VARCHAR(128),
    icon VARCHAR(64),
    sort_order INT DEFAULT 0,
    status SMALLINT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sys_permission_parent_id ON sys_permission(parent_id);
CREATE INDEX IF NOT EXISTS idx_sys_permission_type ON sys_permission(permission_type);
CREATE INDEX IF NOT EXISTS idx_sys_permission_status ON sys_permission(status);

-- 角色权限关联表
CREATE TABLE IF NOT EXISTS sys_role_permission (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_sys_role_permission_role_id ON sys_role_permission(role_id);
CREATE INDEX IF NOT EXISTS idx_sys_role_permission_permission_id ON sys_role_permission(permission_id);

-- 部门表
CREATE TABLE IF NOT EXISTS sys_dept (
    dept_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_id BIGINT DEFAULT 0,
    dept_name VARCHAR(64) NOT NULL,
    dept_code VARCHAR(64),
    leader_id BIGINT,
    phone VARCHAR(16),
    email VARCHAR(64),
    sort_order INT DEFAULT 0,
    status SMALLINT DEFAULT 1,
    create_by BIGINT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted SMALLINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_sys_dept_parent_id ON sys_dept(parent_id);
CREATE INDEX IF NOT EXISTS idx_sys_dept_status ON sys_dept(status);

-- 操作日志表
CREATE TABLE IF NOT EXISTS sys_operation_log (
    log_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    username VARCHAR(64),
    operation_type VARCHAR(32),
    module VARCHAR(64),
    description VARCHAR(255),
    request_method VARCHAR(16),
    request_url VARCHAR(255),
    request_params TEXT,
    response_data TEXT,
    ip_address VARCHAR(64),
    user_agent VARCHAR(255),
    execution_time INT,
    status SMALLINT,
    error_msg TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sys_operation_log_user_id ON sys_operation_log(user_id);
CREATE INDEX IF NOT EXISTS idx_sys_operation_log_module ON sys_operation_log(module);
CREATE INDEX IF NOT EXISTS idx_sys_operation_log_create_time ON sys_operation_log(create_time);

-- 初始化数据

-- 插入默认角色
INSERT INTO sys_role (role_code, role_name, role_type, data_scope, description, status) VALUES
('ROLE_SUPER_ADMIN', '超级管理员', 1, 1, '系统最高权限，可管理所有功能', 1),
('ROLE_ADMIN', '运营管理员', 1, 1, '负责社群运营和用户管理', 1),
('ROLE_DOCTOR', '家庭医生', 1, 3, '提供医疗咨询和健康管理服务', 1),
('ROLE_HEALTH_MANAGER', '健康管家', 1, 3, 'AI协同服务，处理日常咨询', 1),
('ROLE_BENEFIT_ADVISOR', '权益顾问', 1, 1, '管理健康权益和活动', 1),
('ROLE_INSURANCE_ADVISOR', '保险顾问', 1, 3, '提供保险咨询和销售服务', 1)
ON CONFLICT (role_code) DO NOTHING;

-- 插入默认部门
INSERT INTO sys_dept (parent_id, dept_name, dept_code, sort_order, status)
SELECT 0, '总部', 'HQ', 0, 1
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE dept_code = 'HQ');
INSERT INTO sys_dept (parent_id, dept_name, dept_code, sort_order, status)
SELECT 1, '运营部', 'OP', 1, 1
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE dept_code = 'OP');
INSERT INTO sys_dept (parent_id, dept_name, dept_code, sort_order, status)
SELECT 1, '医疗服务部', 'MED', 2, 1
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE dept_code = 'MED');
INSERT INTO sys_dept (parent_id, dept_name, dept_code, sort_order, status)
SELECT 1, '保险服务部', 'INS', 3, 1
WHERE NOT EXISTS (SELECT 1 FROM sys_dept WHERE dept_code = 'INS');

-- 插入默认用户（密码: admin123）
INSERT INTO sys_user (username, password, real_name, phone, email, dept_id, status, create_by) VALUES
('admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iAt6Z5EO', '系统管理员', '13800138000', 'admin@healthcare.com', 1, 1, 1)
ON CONFLICT (username) DO NOTHING;

-- 关联用户角色
INSERT INTO sys_user_role (user_id, role_id) 
SELECT 1, role_id FROM sys_role WHERE role_code = 'ROLE_SUPER_ADMIN'
ON CONFLICT (user_id, role_id) DO NOTHING;
